#!/bin/sh

# Use neovim for vim if present.
alias vi="nvim" vidiff="nvim -d"
alias vis="sudo nvim"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"
	#ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	ax="aria2c -x 10 -s 10 --summary-interval=0" \
	mpa="mpv --no-audio-display"

# Git
alias dotfiles='/usr/bin/git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME'

# This alias is important. It enables the `pauseallmpv` command.
#alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
#alias \
#	magit="nvim -c MagitOnly" \
#	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
#	weath="less -S ~/.local/share/weatherreport" \
