#!/bin/sh

yabar &
xrdb ~/.Xresources &

bspc monitor eDP1 -d I II III

bspc config border_width		2
bspc config window_gap			3
bspc config top_padding			20
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_padding		0
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	true
bspc config history_aware_focus		true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#dd2727"

xsetroot -cursor_name left_ptr
xset s 360 360

bspc rule -a firefox desktop='^2'
bspc rule -a mpv state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
